# datasource configuration
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = ili
quarkus.datasource.password = ili
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:15432/


# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=update

# Clï¿½ privï¿½e
smallrye.jwt.sign.key.location=META-INF/resources/privateKey.pem

# Clï¿½ public
mp.jwt.verify.publickey.location=META-INF/resources/publicKey.pem


quarkus.smallrye-openapi.store-schema-directory=src/main/resources/META-INF/resources/schema

# Enable the Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# Activation du support CORS
quarkus.http.cors=true

# Spécifier l'origine autorisée
quarkus.http.cors.origins=http://localhost:4200, https://a71b-2001-861-3507-5030-3dea-ef7b-f66c-5bd3.ngrok-free.app

# Méthodes HTTP autorisées
quarkus.http.cors.methods=GET,POST,PUT,DELETE

# En-têtes autorisés dans les requêtes
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with

# En-têtes autorisés dans les réponses
quarkus.http.cors.exposed-headers=Content-Disposition,Content-Length,Date,Server,WWW-Authenticate

# Autoriser l'envoi des credentials (cookies, données d'authentification HTTP) dans les requêtes cross-origin
quarkus.http.cors.access-control-allow-credentials=true
